<!DOCTYPE html>
<html lang='en'>

<head>
  <?php include($_SERVER['DOCUMENT_ROOT'] . '/en/lang.php') ?>
  <title>Terms of Service | TAOS Data</title>
  <meta name='description' content='TDengine is an open-source big data platform for IoT. Along with a 10x faster time-series database, it provides caching, stream computing, message queuing, and other functionalities. It is designed and optimized for Internet of Things, Connected Cars, and Industrial IoT. Read the documentation for TDengine here to get started right away.'>
  <meta name='keywords' content='TDengine, Big Data, Open Source, IoT, Connected Cars, Industrial IoT, time-series database, caching, stream computing, message queuing, IT infrastructure monitoring, application performance monitoring, Internet of Things,TAOS Data, Legal, Terms of Service,'>
  <meta name='title' content='Terms of Service | TAOS Data'>
  <meta property='og:site_name' content='TAOS Data' />
  <meta property='og:title' content='Terms of Service | TAOS Data' />
  <meta property='og:type' content='article' />
  <meta property='og:url' content='https://www.taosdata.com/terms-of-service' />
  <meta property='og:description' content='TDengine is an open-source big data platform for IoT. Along with a 10x faster time-series database, it provides caching, stream computing, message queuing, and other functionalities. It is designed and optimized for Internet of Things, Connected Cars, and Industrial IoT. Read the documentation for TDengine here to get started right away.' />
  <?php $s=$_SERVER['DOCUMENT_ROOT']."/$lang";include($s.'/head.php');?>
  <link rel='canonical' href='https://www.taosdata.com/terms-of-service/' />
  <link rel='stylesheet' href='/lib/docs/docs.css'>
</head>

<body>
  <?php include($s.'/header.php'); ?>
  <script>
    $('#documentation-href').addClass('active')
  </script>
  <div class='container-fluid'>
    <main class='content-wrapper'>
      <section class='documentation'>
        <h1>Terms of Service</h1>
        <p><em>Last Updated: July 8, 2019</em></p>
        <p>Thank you for visiting <a href='http://www.taosdata.com' target='_blank' class='url'>www.taosdata.com</a> (the “Site”) and learning more about our IoT Big Data Product and Service (the “Service”). Your use and access of the Site is governed by and subject to the following terms of use (“Terms”). If you do not agree to these Terms, or if you do not agree with our <a href='https://www.taosdata.com/en/privacy/' target='_blank'>Privacy Policy</a>, which is available at <a href='https://www.taosdata.com/en/privacy/' target='_blank'>http://www.taosdata.com/en/privacy</a>, please do not use the Site or the Service. BY ACCESSING, BROWSING, OR OTHERWISE USING THE SITE, YOU REPRESENT THAT: (I) YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTAND AND AGREE TO THESE TERMS OF USE, (II) YOU ARE OF LEGAL AGE TO FORM A BINDING CONTRACT WITH TAOS Data, INC. (“TAOS Data”), AND (III) YOU HAVE THE AUTHORITY TO ENTER INTO THESE TERMS PERSONALLY OR ON BEHALF OF THE ENTITY YOU REPRESENT. IF YOU DO NOT AGREE TO BE BOUND BY THESE TERMS, YOU MAY NOT ACCESS OR USE THE SITE.</p>
        <a class='anchor' id='Email/Member Accounts'></a>
        <h3>Email/Member Accounts</h3>
        <p>In order to use certain features of the Service, you may be asked to input email address or create an account (“Member Account”). You may never use another’s email or Member Account without permission. As part of the account set-up and registration process, you may be asked to select a username and password. You agree to provide true, accurate, current and complete information about yourself as prompted by the Site, and will maintain the accuracy of such registration data. We may refuse to grant you a username for any reason in our sole discretion, including in the event that we determine that such user name impersonates someone else, is illegal, vulgar, or otherwise offensive, or is protected by trademark or other proprietary rights law, or otherwise may cause confusion. You will be responsible for the confidentiality and use of your username and password and agree not to transfer or resell your use of or access to the Site to any third party. You agree to notify TAOS Data immediately of any unauthorized use of your password or any other breach of security. YOU ARE ENTIRELY RESPONSIBLE FOR MAINTAINING THE CONFIDENTIALITY OF YOUR USERNAME AND PASSWORD AND FOR ANY AND ALL ACTIVITIES (INCLUDING PURCHASES, AS APPLICABLE) THAT ARE CONDUCTED THROUGH YOUR ACCOUNT.</p>
        <a class='anchor' id='Your Use of The Service'></a>
        <h3>Your Use of The Service</h3>
        <p>Subject to these Terms and our Privacy Policy, you are granted a limited license to use Site to learn about and potentially access the Service and to copy, display, and use the functionality, materials, features, and services provided by the Site solely for your personal, non-commercial use. If you use the Service, including via your Member Account, you acknowledge and agree that in addition to these Terms, your access to and use of the Service will be subject to the terms and conditions of TAOS Data’s Master SaaS Agreement (“Master Agreement”). In the event of a conflict between these Terms and the Master Agreement, the Master Agreement will prevail.</p>
        <a class='anchor' id='Privacy Policy'></a>
        <h3>Privacy Policy</h3>
        <p>TAOS Data takes your privacy very seriously. TAOS Data’s online <a href='http://www.taosdata.com/en/privacy/' target='_blank'>Privacy Policy</a> is incorporated herein by reference and describes the collection, use, and sharing of certain personally identifiable information that may be provided in connection with the use of the Site. Please read and understand our Privacy Policy before accessing or using the Site.</p>
        <a class='anchor' id='Rights and Restrictions Relating to Site Content'></a>
        <h3>Rights and Restrictions Relating to Site Content</h3>
        <p>This Site and all the materials available on the Site are the property of TAOS Data or licensors, and are protected by copyright, trademark, and other intellectual property laws. The Site is provided solely for your personal noncommercial use. You may not use the Site or the materials available on the Site in a manner that constitutes an infringement of our rights or that has not been authorized by us. More specifically, unless explicitly authorized in these Terms of Service or by the owner of the materials, you may not modify, copy, reproduce, republish, upload, post, transmit, translate, sell, create derivative works, exploit, or distribute in any manner or medium (including by email or other electronic means) any material from the Site. You may, however, from time to time, download and/or copy individual pages of the Site for nonproprietary use, provided that you keep intact all copyright and other proprietary notices. For information about requesting permission to reproduce or distribute materials from the Site, please contact us.</p>
        <a class='anchor' id='User Content'></a>
        <h3>User Content</h3>
        <p>All concepts, ideas, comments, manuscripts, illustrations, and all other materials disclosed or offered to TAOS Data on or in connection with the Site are submitted without any restrictions or expectation of confidentiality. TAOS Data shall have no financial or other obligations to you when you submit such information, nor shall you assert any proprietary or moral right of any kind with respect to such submissions. TAOS Data shall have the unrestricted right to use, publish, reproduce, transmit, download, upload, post, display, incorporate it (in whole or in part) in other works in any form, media or technology now known or later developed, or otherwise distribute your submissions in any manner without notice or compensation to you.</p>
        <p>You acknowledge that TAOS Data reserves the right to, and may from time to time, monitor any and all Information transmitted or received through the Site. TAOS Data, at its sole discretion and without further notice to you, may (but is not obligated to) review, censor or prohibit the transmission or receipt of any Information which TAOS Data deems inappropriate or that violates any term or condition of this agreement. During monitoring, information may be examined, recorded, copied, and used for authorized purposes. Use of the Site, authorized or unauthorized, constitutes consent to such monitoring.</p>
        <p>You may not link, upload, post or transmit any illegal, obscene, offensive or otherwise inappropriate material to the Site. Furthermore, you may not use any of TAOS Data’s proprietary logos, marks, or other distinctive graphics, video, or audio material in your links, without TAOS Data’s express written permission, which TAOS Data may withhold in its sole discretion. You may not link in any manner reasonably likely to (i) imply affiliation with or endorsement or sponsorship by TAOS Data; (ii) cause confusion, mistake, or deception; (iii) dilute TAOS Data’s trademarks or service marks; or (iv) otherwise violate state or federal law.</p>
        <a class='anchor' id='Links'></a>
        <h3>Links</h3>
        <p>The Site may contain links allowing you to leave the Site for other Site that are not under our control (“Linked Site”). TAOS Data provides the linked Site to you only as a convenience and does not endorse any Linked Site. TAOS Data is not responsible for the contents or transmission of any Linked Site or any link contained in a Linked Site or for ensuring that the Linked Site contains no errors or viruses. TAOS Data is not responsible for the terms of use or privacy practices of the Linked Site or any link contained in the Linked Site. Your linking to any Linked Site or any other off-site page or other site is entirely at your own risk. TAOS Data encourages you to carefully read the policies of each site you visit.</p>
        <a class='anchor' id='Arbitration'></a>
        <h3>Arbitration</h3>
        <p>Except to the extent otherwise provided by law, any dispute or claim arising out of or in any way relating to this Terms of Service or the Site shall be finally resolved by arbitration. The arbitration shall be conducted in accordance with the International Institute for Conflict Prevention and Resolution (“CPR”) Rules for Non-Administered Arbitration, except as they may be modified herein or by mutual agreement of the parties. The arbitration shall take place in California or such other location as agreed to by the parties. Notwithstanding the foregoing, the parties consent to the jurisdiction of the federal or state courts having jurisdiction in the location where the arbitration is conducted as to judicial proceedings relating to any aspect of the arbitration, including motions to confirm, vacate, modify or correct an arbitration award. The arbitration shall be governed by the Federal Arbitration Act, 9 U.S.C. § 1, et seq., and judgment upon the award may be entered by any court having jurisdiction thereof or having jurisdiction over the relevant party or its assets. The arbitration shall be conducted by one arbitrator, who shall be selected by agreement of the parties or, failing such agreement within 30 days after the initiation of the arbitration, by the CPR. The parties shall be responsible for paying the costs of the arbitration in accordance with CPR rules. The parties agree that the arbitration shall be kept confidential and that the existence of the proceeding and any element of it shall not be disclosed beyond the tribunal, the parties and their counsel, and any person necessary to the conduct of the proceeding. The confidentiality obligations shall not apply if disclosure is required by law or in judicial or administrative proceedings, or to the extent that disclosure is necessary to enforce the rights arising out of the award, provided that the parties agree to use best efforts to keep such disclosure confidential and agree, subject to court approval, to submit such disclosure to a court only under seal. Claims may not be brought in the arbitration proceeding by or on behalf of a purported class of claimants who are not parties to this engagement letter. This agreement to arbitrate shall constitute an irrevocable waiver of each party’s right to a trial by jury, as well as of rights to discovery or to an appeal that would customarily be available in a judicial proceeding but that may be limited or unavailable in connection with such an arbitration.</p>
        <p>To the extent that this arbitration requirement is found to be entirely unenforceable, you agree that any dispute arising from or relating to this Terms of Service or the Site will be brought exclusively in a court of competent jurisdiction, federal or state, located within California, and in no other jurisdiction, and you hereby consent to personal jurisdiction and venue in, and agree to service of process issued or authorized by, such court.</p>
        <a class='anchor' id='Disclaimers'></a>
        <h3>Disclaimers</h3>
        <p>Without limiting the foregoing, the Site and the Materials and all other features offered via the Site, are provided to you “AS IS” and “AS AVAILABLE” without warranty of any kind, either express or implied, including but not limited to, fitness for a particular purpose, title, or non-infringement. Should applicable law not permit the foregoing exclusion of express or implied warranties, then TAOS Data hereby grants the minimum express or implied warranty required by such applicable law. No advice or information, whether oral or written, obtained by you from TAOS Data, its employees, agents, suppliers or any other persons shall create any warranty, representation or guarantee not expressly stated in this section. Additionally, TAOS Data does not make any warranties that the Site will be uninterrupted, secure or error free or that your use of the Site will meet your expectations, or that the Site, Materials, or any portion thereof, is correct, accurate, or reliable. TAOS Data reserves the right to change any part of the Site at anytime without notice.</p>
        <a class='anchor' id='Limitation of Liability'></a>
        <h3>Limitation of Liability</h3>
        <p>Your use of the Site is at your own risk. Neither TAOS Data, its affiliates, nor any of their respective officers, directors, agents or other representatives will be liable for any damages, direct, indirect, incidental, consequential, special, or punitive, including, without limitation, loss of data, income, profit or goodwill, loss of or damage to property and claims of third parties arising out of your access to or use of the Site or arising out of any action taken in response to or as a result of any Materials or other information available on the Site, however caused, whether based on breach of contract, tort (including negligence), proprietary rights infringement, product liability or otherwise. The foregoing shall apply even if TAOS Data was advised of the possibility of such damages. If you become dissatisfied in any way with the Site, or its Terms of Use or Privacy Policy, your sole and exclusive remedy is to stop your use of the Site. You hereby waive any and all claims against TAOS Data and its affiliates, agents, representatives and licensors arising out of your use of the Site. Because some states do not allow the disclaimer of implied warranties or the exclusion or limitation of certain types of damages, these provisions may not apply to you. If any portion of this limitation on liability is found to be invalid or unenforceable for any reason, then the aggregate liability of TAOS Data and its affiliates shall not exceed one hundred dollars ($100.) The limitation of liability herein is a fundamental element of the basis of the bargain and reflects a fair allocation of risk. The Site would not be provided without such limitations and you agree that the limitations and exclusions of liability, disclaimers and exclusive remedies specified herein will survive even if found to have failed in their essential purpose.</p>
        <a class='anchor' id='Changes to these Terms'></a>
        <h3>Changes to these Terms</h3>
        <p>From time to time, TAOS Data may revise these Terms. When changes are made, TAOS Data will make a new copy of the Terms available at the Site, and will also update the “Last Updated” date above. If TAOS Data makes any material changes, and you have registered to create a Member Account with TAOS Data, TAOS Data will also send an email to you at the last email address you provided to us pursuant to the Terms. Any changes to the Terms will be effective immediately for new users of the Site and will be effective thirty (30) days after posting notice of such changes on the Site for existing users. Your use of the Site following the posting of any revised Terms shall be deemed acceptance of the revised policy. TAOS Data strongly recommends checking Terms periodically. If you disagree with the provisions of these Terms at any time, your sole remedy is to terminate your use of the Site. Continued use of the Site constitutes your agreement to these Terms as in effect.</p>
        <a class='anchor' id='Miscellaneous'></a>
        <h3>Miscellaneous</h3>
        <p>TAOS Data’s failure to enforce any provision of these Terms shall not be deemed a waiver of such provision nor of the right to enforce such provision. If any part of these Terms is determined to be invalid or unenforceable pursuant to applicable law, including, but not limited to, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of these Terms shall continue in effect. Any waiver or failure to enforce any provision of the Terms on one occasion will not be deemed a waiver of any other provision or of such provision on any other occasion. A printed version of these Terms and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to these Terms to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. These Terms are the final, complete and exclusive agreement of the parties with respect to the subject matter hereof and supersedes and merges all prior discussions between the parties with respect to such subject matter.</p>
      </section>
    </main>
  </div>
  <?php include($s.'/footer.php'); ?>
</body>

</html>