<!DOCTYPE html><html lang='en'><head><?php include($_SERVER['DOCUMENT_ROOT'] . '/en/lang.php') ?><title>Contributing | TAOS Data</title><meta name='description' content='TDengine is an open-source big data platform for IoT. Along with a 10x faster time-series database, it provides caching, stream computing, message queuing, and other functionalities. It is designed and optimized for Internet of Things, Connected Cars, and Industrial IoT.'><meta name='keywords' content='TDengine, Big Data, Open Source, IoT, Connected Cars, Industrial IoT, time-series database, caching, stream computing, message queuing, IT infrastructure monitoring, application performance monitoring, Internet of Things,TAOS Data, Documentation, programming, coding, syntax, frequently asked questions, questions, faq'><meta name='title' content='Contributing | TAOS Data'><meta property='og:site_name' content='TAOS Data'/><meta property='og:title' content='Documentation | TAOS Data'/><meta property='og:type' content='article'/><meta property='og:url' content='https://www.taosdata.com/<?php echo $lang; ?>/documentation/contributor_license_agreement/index.php'/><meta property='og:description' content='TDengine is an open-source big data platform for IoT. Along with a 10x faster time-series database, it provides caching, stream computing, message queuing, and other functionalities. It is designed and optimized for Internet of Things, Connected Cars, and Industrial IoT.' /><?php $s=$_SERVER['DOCUMENT_ROOT']."/$lang";include($s.'/head.php');?><link rel='canonical' href='https://www.taosdata.com/<?php echo $lang; ?>/documentation/contributor_license_agreement/index.php'/><link rel='stylesheet' href='/lib/docs/taosdataprettify.css'><link rel='stylesheet' href='/lib/docs/docs.css'><script src='/lib/docs/prettify.js'></script><script src='/lib/docs/prettyprint-sql.js'></script></head><body><?php include($s.'/header.php'); ?><script>$('#documentation-href').addClass('active')</script><div class='container-fluid'><main class='content-wrapper'><section class='documentation'><h1>TAOS Data Contributor License Agreement</h1>
<p>This TAOS Data Contributor License Agreement (CLA) applies to any contribution you make to any TAOS Data projects. If you are representing your employing organization to sign this agreement, please warrant that you have the authority to grant the agreement.</p>
<a class='anchor' id='Terms'></a><h2>Terms</h2>
<p><strong>"TAOS Data"</strong>, <strong>"we"</strong>, <strong>"our"</strong> and <strong>"us"</strong> means TAOS Data, inc.</p>
<p><strong>"You"</strong> and <strong>"your"</strong> means you or the organization you are on behalf of to sign this agreement.</p>
<p><strong>"Contribution"</strong> means any original work you, or the organization you represent submit to TAOS Data for any project in any manner.</p>
<a class='anchor' id='Copyright-License'></a><h2>Copyright License</h2>
<p>All rights of your Contribution submitted to TAOS Data in any manner are granted to TAOS Data and recipients of software distributed by TAOS Data. You waive any rights that my affect our ownership of the copyright and grant to us a perpetual, worldwide, transferable, non-exclusive, no-charge, royalty-free, irrevocable, and sublicensable license to use, reproduce, prepare derivative works of, publicly display, publicly perform, sublicense, and distribute Contributions and any derivative work created based on a Contribution.</p>
<a class='anchor' id='Patent-License'></a><h2>Patent License</h2>
<p>With respect to any patents you own or that you can license without payment to any third party, you grant to us and to any recipient of software distributed by us, a perpetual, worldwide, transferable, non-exclusive, no-charge, royalty-free, irrevocable patent license to make, have make, use, sell, offer to sell, import, and otherwise transfer the Contribution in whole or in part, alone or included in any product under any patent you own, or license from a third party, that is necessarily infringed by the Contribution or by combination of the Contribution with any Work.</p>
<a class='anchor' id='Your-Representations-and-Warranties'></a><h2>Your Representations and Warranties</h2>
<p>You represent and warrant that:</p>
<ul>
<li><p>the Contribution you submit is an original work that you can legally grant the rights set out in this agreement.</p></li>
<li><p>the Contribution you submit and licenses you granted does not and will not, infringe the rights of any third party.</p></li>
<li><p>you are not aware of any pending or threatened claims, suits, actions, or charges pertaining to the contributions. You also warrant to notify TAOS Data immediately if you become aware of any such actual or potential claims, suits, actions, allegations or charges.</p></li>
</ul>
<a class='anchor' id='Support'></a><h2>Support</h2>
<p>You are not obligated to support your Contribution except you volunteer to provide support. If you want, you can provide for a fee.</p>
<p><strong>I agree and accept on behalf of myself and behalf of my organization:</strong></p></section></main></div><?php include($s.'/footer.php'); ?><script>$('pre').addClass('prettyprint linenums');PR.prettyPrint()</script><script src='/lib/docs/liner.js'></script></body></html>